# Generated by Django 5.1.1 on 2024-10-19 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_text_question_option_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
